apiVersion: v1
kind: Service
metadata:
  name: multi-repo2-service
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: http
  selector:
    app: multi-repo2

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multi-repo2-info
  labels:
    account: multi-repo2